
networks:
  loki:
  grafana:

services:
  node-app:
    image: nazia141/node_repository:3.0 
    container_name: my-node-app-container
    environment:
      - NODE_ENV=production  
    network_mode: host
    volumes:
      - ./logs/app.log:/var/logs/app.log 

  loki:
    image: grafana/loki:2.8.2
    volumes:
      - /home/nazia/promptail-docker/loki:/etc/loki/
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    # networks:
    #   - loki
    network_mode: host

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
      - /home/nazia/promptail-docker/promptail:/etc/promtail 
      - ./logs/app.log:/var/logs/app.log 
    command: -config.file=/etc/promtail/promptail-config.yaml
    network_mode: host


  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=blackmirror1-singlestat-math-panel
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://localhost:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    network_mode: host
    # networks:
    #   - grafana
    depends_on:
      - loki


volumes:
  loki-data:
  tempo-data: